name: Test the analyze and test workflow

on:
  push:
    branches-ignore: [ "master" ]
  workflow_dispatch:

jobs:
  analyze-test:
    uses: weewx-extensions/development_tools/.github/workflows/analyze-test.yml@v3
    with:
      module-name: 'pushover'
      #pip-list: 'paho-mqtt'
      #package-list: 'mosquitto'
      function-test: false
      integration-test: false
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
